bq-dbt-proj:
  outputs:
    dev:
      dataset: Congress
      fixed_retries: 1
      keyfile: "{{ env_var('DBT_GOOGLE_CREDENTIALS') }}"
      project: "{{ env_var('DBT_GCP_PROJECT') }}"
      location: US
      method: service-account
      priority: interactive
      threads: 4
      timeout_seconds: 300
      type: bigquery
  target: dev
 
  
