house_votes_schema = [{'name': 'rollcall_vote',
  'type': 'RECORD',
  'mode': 'NULLABLE',
  'fields': [{'name': 'vote_metadata',
    'type': 'RECORD',
    'mode': 'NULLABLE',
    'fields': [{'name': 'majority', 'type': 'STRING', 'mode': 'NULLABLE'},
     {'name': 'congress', 'type': 'STRING', 'mode': 'NULLABLE'},
     {'name': 'session', 'type': 'STRING', 'mode': 'NULLABLE'},
     {'name': 'chamber', 'type': 'STRING', 'mode': 'NULLABLE'},
     {'name': 'rollcall_num', 'type': 'STRING', 'mode': 'NULLABLE'},
     {'name': 'legis_num', 'type': 'STRING', 'mode': 'NULLABLE'},
     {'name': 'vote_question', 'type': 'STRING', 'mode': 'NULLABLE'},
     {'name': 'vote_type', 'type': 'STRING', 'mode': 'NULLABLE'},
     {'name': 'vote_result', 'type': 'STRING', 'mode': 'NULLABLE'},
     {'name': 'action_date', 'type': 'STRING', 'mode': 'NULLABLE'},
     {'name': 'action_time',
      'type': 'RECORD',
      'mode': 'NULLABLE',
      'fields': [{'name': 'time_etz', 'type': 'STRING', 'mode': 'NULLABLE'},
       {'name': 'text', 'type': 'STRING', 'mode': 'NULLABLE'}]},
     {'name': 'vote_desc', 'type': 'STRING', 'mode': 'NULLABLE'},
     {'name': 'vote_totals',
      'type': 'RECORD',
      'mode': 'NULLABLE',
      'fields': [{'name': 'totals_by_party_header',
        'type': 'RECORD',
        'mode': 'NULLABLE',
        'fields': [{'name': 'party_header',
          'type': 'STRING',
          'mode': 'NULLABLE'},
         {'name': 'yea_header', 'type': 'STRING', 'mode': 'NULLABLE'},
         {'name': 'nay_header', 'type': 'STRING', 'mode': 'NULLABLE'},
         {'name': 'present_header', 'type': 'STRING', 'mode': 'NULLABLE'},
         {'name': 'not_voting_header', 'type': 'STRING', 'mode': 'NULLABLE'}]},
       {'name': 'totals_by_party',
        'type': 'RECORD',
        'mode': 'REPEATED',
        'fields': [{'name': 'party', 'type': 'STRING', 'mode': 'NULLABLE'},
         {'name': 'yea_total', 'type': 'STRING', 'mode': 'NULLABLE'},
         {'name': 'nay_total', 'type': 'STRING', 'mode': 'NULLABLE'},
         {'name': 'present_total', 'type': 'STRING', 'mode': 'NULLABLE'},
         {'name': 'not_voting_total', 'type': 'STRING', 'mode': 'NULLABLE'}]},
       {'name': 'totals_by_vote',
        'type': 'RECORD',
        'mode': 'NULLABLE',
        'fields': [{'name': 'total_stub',
          'type': 'STRING',
          'mode': 'NULLABLE'},
         {'name': 'yea_total', 'type': 'STRING', 'mode': 'NULLABLE'},
         {'name': 'nay_total', 'type': 'STRING', 'mode': 'NULLABLE'},
         {'name': 'present_total', 'type': 'STRING', 'mode': 'NULLABLE'},
         {'name': 'not_voting_total',
          'type': 'STRING',
          'mode': 'NULLABLE'}]}]}]},
   {'name': 'vote_data',
    'type': 'RECORD',
    'mode': 'NULLABLE',
    'fields': [{'name': 'recorded_vote',
      'type': 'RECORD',
      'mode': 'REPEATED',
      'fields': [{'name': 'legislator',
        'type': 'RECORD',
        'mode': 'NULLABLE',
        'fields': [{'name': 'name_id', 'type': 'STRING', 'mode': 'NULLABLE'},
         {'name': 'sort_field', 'type': 'STRING', 'mode': 'NULLABLE'},
         {'name': 'unaccented_name', 'type': 'STRING', 'mode': 'NULLABLE'},
         {'name': 'party', 'type': 'STRING', 'mode': 'NULLABLE'},
         {'name': 'state', 'type': 'STRING', 'mode': 'NULLABLE'},
         {'name': 'role', 'type': 'STRING', 'mode': 'NULLABLE'},
         {'name': 'text', 'type': 'STRING', 'mode': 'NULLABLE'}]},
       {'name': 'vote', 'type': 'STRING', 'mode': 'NULLABLE'}]}]}]},
 {'name': 'chamber', 'type': 'STRING', 'mode': 'NULLABLE'},
 {'name': 'bill_number', 'type': 'INT64', 'mode': 'NULLABLE'},
 {'name': 'bill_type', 'type': 'STRING', 'mode': 'NULLABLE'}]

senate_votes_schema = [{'name': 'roll_call_vote',
  'type': 'RECORD',
  'mode': 'NULLABLE',
  'fields': [{'name': 'congress', 'type': 'STRING', 'mode': 'NULLABLE'},
   {'name': 'session', 'type': 'STRING', 'mode': 'NULLABLE'},
   {'name': 'congress_year', 'type': 'STRING', 'mode': 'NULLABLE'},
   {'name': 'vote_number', 'type': 'STRING', 'mode': 'NULLABLE'},
   {'name': 'vote_date', 'type': 'STRING', 'mode': 'NULLABLE'},
   {'name': 'modify_date', 'type': 'STRING', 'mode': 'NULLABLE'},
   {'name': 'vote_question_text', 'type': 'STRING', 'mode': 'NULLABLE'},
   {'name': 'vote_document_text', 'type': 'STRING', 'mode': 'NULLABLE'},
   {'name': 'vote_result_text', 'type': 'STRING', 'mode': 'NULLABLE'},
   {'name': 'question', 'type': 'STRING', 'mode': 'NULLABLE'},
   {'name': 'vote_title', 'type': 'STRING', 'mode': 'NULLABLE'},
   {'name': 'majority_requirement', 'type': 'STRING', 'mode': 'NULLABLE'},
   {'name': 'vote_result', 'type': 'STRING', 'mode': 'NULLABLE'},
   {'name': 'document',
    'type': 'RECORD',
    'mode': 'NULLABLE',
    'fields': [{'name': 'document_congress',
      'type': 'STRING',
      'mode': 'NULLABLE'},
     {'name': 'document_type', 'type': 'STRING', 'mode': 'NULLABLE'},
     {'name': 'document_number', 'type': 'STRING', 'mode': 'NULLABLE'},
     {'name': 'document_name', 'type': 'STRING', 'mode': 'NULLABLE'},
     {'name': 'document_title', 'type': 'STRING', 'mode': 'NULLABLE'},
     {'name': 'document_short_title', 'type': 'STRING', 'mode': 'NULLABLE'}]},
   {'name': 'amendment',
    'type': 'RECORD',
    'mode': 'NULLABLE',
    'fields': [{'name': 'amendment_number',
      'type': 'STRING',
      'mode': 'NULLABLE'},
     {'name': 'amendment_to_amendment_number',
      'type': 'STRING',
      'mode': 'NULLABLE'},
     {'name': 'amendment_to_amendment_to_amendment_number',
      'type': 'STRING',
      'mode': 'NULLABLE'},
     {'name': 'amendment_to_document_number',
      'type': 'STRING',
      'mode': 'NULLABLE'},
     {'name': 'amendment_to_document_short_title',
      'type': 'STRING',
      'mode': 'NULLABLE'},
     {'name': 'amendment_purpose', 'type': 'STRING', 'mode': 'NULLABLE'}]},
   {'name': 'count',
    'type': 'RECORD',
    'mode': 'NULLABLE',
    'fields': [{'name': 'yeas', 'type': 'STRING', 'mode': 'NULLABLE'},
     {'name': 'nays', 'type': 'STRING', 'mode': 'NULLABLE'},
     {'name': 'present', 'type': 'STRING', 'mode': 'NULLABLE'},
     {'name': 'absent', 'type': 'STRING', 'mode': 'NULLABLE'}]},
   {'name': 'tie_breaker',
    'type': 'RECORD',
    'mode': 'NULLABLE',
    'fields': [{'name': 'by_whom', 'type': 'STRING', 'mode': 'NULLABLE'},
     {'name': 'tie_breaker_vote', 'type': 'STRING', 'mode': 'NULLABLE'}]},
   {'name': 'members',
    'type': 'RECORD',
    'mode': 'NULLABLE',
    'fields': [{'name': 'member',
      'type': 'RECORD',
      'mode': 'REPEATED',
      'fields': [{'name': 'member_full', 'type': 'STRING', 'mode': 'NULLABLE'},
       {'name': 'last_name', 'type': 'STRING', 'mode': 'NULLABLE'},
       {'name': 'first_name', 'type': 'STRING', 'mode': 'NULLABLE'},
       {'name': 'party', 'type': 'STRING', 'mode': 'NULLABLE'},
       {'name': 'state', 'type': 'STRING', 'mode': 'NULLABLE'},
       {'name': 'vote_cast', 'type': 'STRING', 'mode': 'NULLABLE'},
       {'name': 'lis_member_id', 'type': 'STRING', 'mode': 'NULLABLE'}]}]}]},
 {'name': 'chamber', 'type': 'STRING', 'mode': 'NULLABLE'},
 {'name': 'bill_number', 'type': 'INT64', 'mode': 'NULLABLE'},
 {'name': 'bill_type', 'type': 'STRING', 'mode': 'NULLABLE'}]

bill_schema = [{"name": "number", "type": "STRING", "mode": "NULLABLE"},
    {"name": "updateDate", "type": "STRING", "mode": "NULLABLE"},
    {"name": "updateDateIncludingText", "type": "STRING", "mode": "NULLABLE"},
    {"name": "originChamber", "type": "STRING", "mode": "NULLABLE"},
    {"name": "originChamberCode", "type": "STRING", "mode": "NULLABLE"},
    {"name": "type", "type": "STRING", "mode": "NULLABLE"},
    {"name": "introducedDate", "type": "STRING", "mode": "NULLABLE"},
    {"name": "congress", "type": "STRING", "mode": "NULLABLE"},
    {"name": "constitutionalAuthorityStatementText", "type": "STRING", "mode": "NULLABLE"},
    {"name": "committees", "type": "JSON", "mode": "NULLABLE"},
    {"name": "relatedBills", "type": "JSON", "mode": "NULLABLE"},
    {"name": "actions", "type": "JSON", "mode": "NULLABLE"},
    {"name": "sponsors", "type": "JSON", "mode": "NULLABLE"},
    {"name": "cosponsors", "type": "JSON", "mode": "NULLABLE"},
    {"name": "policyArea", "type": "JSON", "mode": "NULLABLE"},
    {"name": "subjects", "type": "JSON", "mode": "NULLABLE"},
    {"name": "summaries", "type": "JSON", "mode": "NULLABLE"},
    {"name": "title", "type": "STRING", "mode": "NULLABLE"},
    {"name": "titles", "type": "JSON", "mode": "NULLABLE"},
    {"name": "textVersions", "type": "JSON", "mode": "NULLABLE"},
    {"name": "latestAction", "type": "JSON", "mode": "NULLABLE"},
    {"name": "committeeReports", "type": "JSON", "mode": "NULLABLE"},
    {"name": "cboCostEstimates", "type": "JSON", "mode": "NULLABLE"},
    {"name": "laws", "type": "JSON", "mode": "NULLABLE"},
    {"name": "amendments", "type": "JSON", "mode": "NULLABLE"},
    {"name": "cdata", "type": "JSON", "mode": "NULLABLE"}]

# bill_schema = [[{'name': 'number', 'type': 'STRING', 'mode': 'NULLABLE'},
#  {'name': 'updateDate', 'type': 'STRING', 'mode': 'NULLABLE'},
#  {'name': 'updateDateIncludingText', 'type': 'STRING', 'mode': 'NULLABLE'},
#  {'name': 'originChamber', 'type': 'STRING', 'mode': 'NULLABLE'},
#  {'name': 'originChamberCode', 'type': 'STRING', 'mode': 'NULLABLE'},
#  {'name': 'type', 'type': 'STRING', 'mode': 'NULLABLE'},
#  {'name': 'introducedDate', 'type': 'STRING', 'mode': 'NULLABLE'},
#  {'name': 'congress', 'type': 'STRING', 'mode': 'NULLABLE'},
#  {'name': 'constitutionalAuthorityStatementText',
#   'type': 'STRING',
#   'mode': 'NULLABLE'},
#  {'name': 'committees',
#   'type': 'RECORD',
#   'mode': 'NULLABLE',
#   'fields': [{'name': 'item',
#     'type': 'RECORD',
#     'mode': 'REPEATED',
#     'fields': [{'name': 'systemCode', 'type': 'STRING', 'mode': 'NULLABLE'},
#      {'name': 'name', 'type': 'STRING', 'mode': 'NULLABLE'},
#      {'name': 'chamber', 'type': 'STRING', 'mode': 'NULLABLE'},
#      {'name': 'type', 'type': 'STRING', 'mode': 'NULLABLE'},
#      {'name': 'activities',
#       'type': 'RECORD',
#       'mode': 'NULLABLE',
#       'fields': [{'name': 'item',
#         'type': 'RECORD',
#         'mode': 'REPEATED',
#         'fields': [{'name': 'name', 'type': 'STRING', 'mode': 'NULLABLE'},
#          {'name': 'date', 'type': 'STRING', 'mode': 'NULLABLE'}]}]},
#      {'name': 'subcommittees',
#       'type': 'RECORD',
#       'mode': 'NULLABLE',
#       'fields': [{'name': 'item',
#         'type': 'RECORD',
#         'mode': 'REPEATED',
#         'fields': [{'name': 'systemCode',
#           'type': 'STRING',
#           'mode': 'NULLABLE'},
#          {'name': 'name', 'type': 'STRING', 'mode': 'NULLABLE'},
#          {'name': 'activities',
#           'type': 'RECORD',
#           'mode': 'NULLABLE',
#           'fields': [{'name': 'item',
#             'type': 'RECORD',
#             'mode': 'REPEATED',
#             'fields': [{'name': 'name', 'type': 'STRING', 'mode': 'NULLABLE'},
#              {'name': 'date',
#               'type': 'STRING',
#               'mode': 'NULLABLE'}]}]}]}]}]}]},
#  {'name': 'relatedBills',
#   'type': 'RECORD',
#   'mode': 'NULLABLE',
#   'fields': [{'name': 'item',
#     'type': 'RECORD',
#     'mode': 'REPEATED',
#     'fields': [{'name': 'title', 'type': 'STRING', 'mode': 'NULLABLE'},
#      {'name': 'congress', 'type': 'STRING', 'mode': 'NULLABLE'},
#      {'name': 'number', 'type': 'STRING', 'mode': 'NULLABLE'},
#      {'name': 'type', 'type': 'STRING', 'mode': 'NULLABLE'},
#      {'name': 'latestAction',
#       'type': 'RECORD',
#       'mode': 'NULLABLE',
#       'fields': [{'name': 'actionDate', 'type': 'STRING', 'mode': 'NULLABLE'},
#        {'name': 'text', 'type': 'STRING', 'mode': 'NULLABLE'},
#        {'name': 'actionTime', 'type': 'STRING', 'mode': 'NULLABLE'}]},
#      {'name': 'relationshipDetails',
#       'type': 'RECORD',
#       'mode': 'NULLABLE',
#       'fields': [{'name': 'item',
#         'type': 'RECORD',
#         'mode': 'REPEATED',
#         'fields': [{'name': 'type', 'type': 'STRING', 'mode': 'NULLABLE'},
#          {'name': 'identifiedBy',
#           'type': 'STRING',
#           'mode': 'NULLABLE'}]}]}]}]},
#  {'name': 'actions',
#   'type': 'RECORD',
#   'mode': 'NULLABLE',
#   'fields': [{'name': 'item',
#     'type': 'RECORD',
#     'mode': 'REPEATED',
#     'fields': [{'name': 'actionDate', 'type': 'STRING', 'mode': 'NULLABLE'},
#      {'name': 'text', 'type': 'STRING', 'mode': 'NULLABLE'},
#      {'name': 'type', 'type': 'STRING', 'mode': 'NULLABLE'},
#      {'name': 'actionCode', 'type': 'STRING', 'mode': 'NULLABLE'},
#      {'name': 'sourceSystem',
#       'type': 'RECORD',
#       'mode': 'NULLABLE',
#       'fields': [{'name': 'code', 'type': 'STRING', 'mode': 'NULLABLE'},
#        {'name': 'name', 'type': 'STRING', 'mode': 'NULLABLE'}]},
#      {'name': 'committees',
#       'type': 'RECORD',
#       'mode': 'NULLABLE',
#       'fields': [{'name': 'item',
#         'type': 'RECORD',
#         'mode': 'REPEATED',
#         'fields': [{'name': 'systemCode',
#           'type': 'STRING',
#           'mode': 'NULLABLE'},
#          {'name': 'name', 'type': 'STRING', 'mode': 'NULLABLE'}]}]},
#      {'name': 'calendarNumber',
#       'type': 'RECORD',
#       'mode': 'NULLABLE',
#       'fields': [{'name': 'calendar', 'type': 'STRING', 'mode': 'NULLABLE'}]},
#      {'name': 'actionTime', 'type': 'STRING', 'mode': 'NULLABLE'},
#      {'name': 'recordedVotes',
#       'type': 'RECORD',
#       'mode': 'NULLABLE',
#       'fields': [{'name': 'recordedVote',
#         'type': 'RECORD',
#         'mode': 'NULLABLE',
#         'fields': [{'name': 'rollNumber',
#           'type': 'STRING',
#           'mode': 'NULLABLE'},
#          {'name': 'url', 'type': 'STRING', 'mode': 'NULLABLE'},
#          {'name': 'chamber', 'type': 'STRING', 'mode': 'NULLABLE'},
#          {'name': 'congress', 'type': 'STRING', 'mode': 'NULLABLE'},
#          {'name': 'date', 'type': 'STRING', 'mode': 'NULLABLE'},
#          {'name': 'sessionNumber',
#           'type': 'STRING',
#           'mode': 'NULLABLE'}]}]}]}]},
#  {'name': 'sponsors',
#   'type': 'RECORD',
#   'mode': 'NULLABLE',
#   'fields': [{'name': 'item',
#     'type': 'RECORD',
#     'mode': 'REPEATED',
#     'fields': [{'name': 'bioguideId', 'type': 'STRING', 'mode': 'NULLABLE'},
#      {'name': 'fullName', 'type': 'STRING', 'mode': 'NULLABLE'},
#      {'name': 'firstName', 'type': 'STRING', 'mode': 'NULLABLE'},
#      {'name': 'lastName', 'type': 'STRING', 'mode': 'NULLABLE'},
#      {'name': 'party', 'type': 'STRING', 'mode': 'NULLABLE'},
#      {'name': 'state', 'type': 'STRING', 'mode': 'NULLABLE'},
#      {'name': 'middleName', 'type': 'STRING', 'mode': 'NULLABLE'},
#      {'name': 'district', 'type': 'STRING', 'mode': 'NULLABLE'},
#      {'name': 'isByRequest', 'type': 'STRING', 'mode': 'NULLABLE'}]}]},
#  {'name': 'cosponsors',
#   'type': 'RECORD',
#   'mode': 'NULLABLE',
#   'fields': [{'name': 'item',
#     'type': 'RECORD',
#     'mode': 'REPEATED',
#     'fields': [{'name': 'bioguideId', 'type': 'STRING', 'mode': 'NULLABLE'},
#      {'name': 'fullName', 'type': 'STRING', 'mode': 'NULLABLE'},
#      {'name': 'firstName', 'type': 'STRING', 'mode': 'NULLABLE'},
#      {'name': 'lastName', 'type': 'STRING', 'mode': 'NULLABLE'},
#      {'name': 'party', 'type': 'STRING', 'mode': 'NULLABLE'},
#      {'name': 'state', 'type': 'STRING', 'mode': 'NULLABLE'},
#      {'name': 'district', 'type': 'STRING', 'mode': 'NULLABLE'},
#      {'name': 'sponsorshipDate', 'type': 'STRING', 'mode': 'NULLABLE'},
#      {'name': 'isOriginalCosponsor', 'type': 'STRING', 'mode': 'NULLABLE'},
#      {'name': 'middleName', 'type': 'STRING', 'mode': 'NULLABLE'},
#      {'name': 'sponsorshipWithdrawnDate',
#       'type': 'STRING',
#       'mode': 'NULLABLE'}]}]},
#  {'name': 'policyArea',
#   'type': 'RECORD',
#   'mode': 'REPEATED',
#   'fields': [{'name': 'name', 'type': 'STRING', 'mode': 'NULLABLE'}]},
#  {'name': 'subjects',
#   'type': 'RECORD',
#   'mode': 'REPEATED',
#   'fields': [{'name': 'legislativeSubjects',
#     'type': 'RECORD',
#     'mode': 'NULLABLE',
#     'fields': [{'name': 'item',
#       'type': 'RECORD',
#       'mode': 'REPEATED',
#       'fields': [{'name': 'name', 'type': 'STRING', 'mode': 'NULLABLE'},
#        {'name': 'updateDate', 'type': 'STRING', 'mode': 'NULLABLE'}]}]},
#    {'name': 'policyArea',
#     'type': 'RECORD',
#     'mode': 'REPEATED',
#     'fields': [{'name': 'name', 'type': 'STRING', 'mode': 'NULLABLE'},
#      {'name': 'updateDate', 'type': 'STRING', 'mode': 'NULLABLE'}]}]},
#  {'name': 'summaries',
#   'type': 'RECORD',
#   'mode': 'NULLABLE',
#   'fields': [{'name': 'summary',
#     'type': 'RECORD',
#     'mode': 'REPEATED',
#     'fields': [{'name': 'versionCode', 'type': 'STRING', 'mode': 'NULLABLE'},
#      {'name': 'actionDate', 'type': 'STRING', 'mode': 'NULLABLE'},
#      {'name': 'actionDesc', 'type': 'STRING', 'mode': 'NULLABLE'},
#      {'name': 'updateDate', 'type': 'STRING', 'mode': 'NULLABLE'},
#      {'name': 'text', 'type': 'STRING', 'mode': 'NULLABLE'}]}]},
#  {'name': 'title', 'type': 'STRING', 'mode': 'NULLABLE'},
#  {'name': 'titles',
#   'type': 'RECORD',
#   'mode': 'NULLABLE',
#   'fields': [{'name': 'item',
#     'type': 'RECORD',
#     'mode': 'REPEATED',
#     'fields': [{'name': 'titleType', 'type': 'STRING', 'mode': 'NULLABLE'},
#      {'name': 'titleTypeCode', 'type': 'STRING', 'mode': 'NULLABLE'},
#      {'name': 'title', 'type': 'STRING', 'mode': 'NULLABLE'},
#      {'name': 'updateDate', 'type': 'STRING', 'mode': 'NULLABLE'},
#      {'name': 'chamberCode', 'type': 'STRING', 'mode': 'NULLABLE'},
#      {'name': 'chamberName', 'type': 'STRING', 'mode': 'NULLABLE'},
#      {'name': 'billTextVersionName', 'type': 'STRING', 'mode': 'NULLABLE'},
#      {'name': 'billTextVersionCode', 'type': 'STRING', 'mode': 'NULLABLE'}]}]},
#  {'name': 'textVersions',
#   'type': 'RECORD',
#   'mode': 'NULLABLE',
#   'fields': [{'name': 'item',
#     'type': 'RECORD',
#     'mode': 'REPEATED',
#     'fields': [{'name': 'type', 'type': 'STRING', 'mode': 'NULLABLE'},
#      {'name': 'date', 'type': 'STRING', 'mode': 'NULLABLE'},
#      {'name': 'formats',
#       'type': 'RECORD',
#       'mode': 'NULLABLE',
#       'fields': [{'name': 'item',
#         'type': 'RECORD',
#         'mode': 'REPEATED',
#         'fields': [{'name': 'url',
#           'type': 'STRING',
#           'mode': 'NULLABLE'}]}]}]}]},
#  {'name': 'latestAction',
#   'type': 'RECORD',
#   'mode': 'NULLABLE',
#   'fields': [{'name': 'actionDate', 'type': 'STRING', 'mode': 'NULLABLE'},
#    {'name': 'text', 'type': 'STRING', 'mode': 'NULLABLE'},
#    {'name': 'actionTime', 'type': 'STRING', 'mode': 'NULLABLE'}]},
#  {'name': 'committeeReports',
#   'type': 'RECORD',
#   'mode': 'NULLABLE',
#   'fields': [{'name': 'committeeReport',
#     'type': 'RECORD',
#     'mode': 'REPEATED',
#     'fields': [{'name': 'citation', 'type': 'STRING', 'mode': 'NULLABLE'}]}]},
#  {'name': 'cboCostEstimates',
#   'type': 'RECORD',
#   'mode': 'NULLABLE',
#   'fields': [{'name': 'item',
#     'type': 'RECORD',
#     'mode': 'REPEATED',
#     'fields': [{'name': 'pubDate', 'type': 'STRING', 'mode': 'NULLABLE'},
#      {'name': 'title', 'type': 'STRING', 'mode': 'NULLABLE'},
#      {'name': 'url', 'type': 'STRING', 'mode': 'NULLABLE'},
#      {'name': 'description', 'type': 'STRING', 'mode': 'NULLABLE'}]}]},
#  {'name': 'laws',
#   'type': 'RECORD',
#   'mode': 'NULLABLE',
#   'fields': [{'name': 'item',
#     'type': 'RECORD',
#     'mode': 'REPEATED',
#     'fields': [{'name': 'type', 'type': 'STRING', 'mode': 'NULLABLE'},
#      {'name': 'number', 'type': 'STRING', 'mode': 'NULLABLE'}]}]},
#  {'name': 'amendments',
#   'type': 'RECORD',
#   'mode': 'NULLABLE',
#   'fields': [{'name': 'amendment',
#     'type': 'RECORD',
#     'mode': 'REPEATED',
#     'fields': [{'name': 'number', 'type': 'STRING', 'mode': 'NULLABLE'},
#      {'name': 'congress', 'type': 'STRING', 'mode': 'NULLABLE'},
#      {'name': 'type', 'type': 'STRING', 'mode': 'NULLABLE'},
#      {'name': 'purpose', 'type': 'STRING', 'mode': 'NULLABLE'},
#      {'name': 'updateDate', 'type': 'STRING', 'mode': 'NULLABLE'},
#      {'name': 'latestAction',
#       'type': 'RECORD',
#       'mode': 'NULLABLE',
#       'fields': [{'name': 'actionDate', 'type': 'STRING', 'mode': 'NULLABLE'},
#        {'name': 'text', 'type': 'STRING', 'mode': 'NULLABLE'},
#        {'name': 'links',
#         'type': 'RECORD',
#         'mode': 'NULLABLE',
#         'fields': [{'name': 'link',
#           'type': 'RECORD',
#           'mode': 'NULLABLE',
#           'fields': [{'name': 'name', 'type': 'STRING', 'mode': 'NULLABLE'},
#            {'name': 'url', 'type': 'STRING', 'mode': 'NULLABLE'}]}]},
#        {'name': 'actionTime', 'type': 'STRING', 'mode': 'NULLABLE'}]},
#      {'name': 'sponsors',
#       'type': 'RECORD',
#       'mode': 'NULLABLE',
#       'fields': [{'name': 'item',
#         'type': 'RECORD',
#         'mode': 'REPEATED',
#         'fields': [{'name': 'bioguideId',
#           'type': 'STRING',
#           'mode': 'NULLABLE'},
#          {'name': 'fullName', 'type': 'STRING', 'mode': 'NULLABLE'},
#          {'name': 'firstName', 'type': 'STRING', 'mode': 'NULLABLE'},
#          {'name': 'lastName', 'type': 'STRING', 'mode': 'NULLABLE'},
#          {'name': 'party', 'type': 'STRING', 'mode': 'NULLABLE'},
#          {'name': 'state', 'type': 'STRING', 'mode': 'NULLABLE'},
#          {'name': 'middleName', 'type': 'STRING', 'mode': 'NULLABLE'},
#          {'name': 'district', 'type': 'STRING', 'mode': 'NULLABLE'},
#          {'name': 'name', 'type': 'STRING', 'mode': 'NULLABLE'}]}]},
#      {'name': 'cosponsors',
#       'type': 'RECORD',
#       'mode': 'NULLABLE',
#       'fields': [{'name': 'countIncludingWithdrawnCosponsors',
#         'type': 'STRING',
#         'mode': 'NULLABLE'},
#        {'name': 'count', 'type': 'STRING', 'mode': 'NULLABLE'},
#        {'name': 'item',
#         'type': 'RECORD',
#         'mode': 'REPEATED',
#         'fields': [{'name': 'bioguideId',
#           'type': 'STRING',
#           'mode': 'NULLABLE'},
#          {'name': 'fullName', 'type': 'STRING', 'mode': 'NULLABLE'},
#          {'name': 'firstName', 'type': 'STRING', 'mode': 'NULLABLE'},
#          {'name': 'lastName', 'type': 'STRING', 'mode': 'NULLABLE'},
#          {'name': 'party', 'type': 'STRING', 'mode': 'NULLABLE'},
#          {'name': 'state', 'type': 'STRING', 'mode': 'NULLABLE'},
#          {'name': 'middleName', 'type': 'STRING', 'mode': 'NULLABLE'},
#          {'name': 'sponsorshipDate', 'type': 'STRING', 'mode': 'NULLABLE'},
#          {'name': 'isOriginalCosponsor',
#           'type': 'STRING',
#           'mode': 'NULLABLE'}]}]},
#      {'name': 'proposedDate', 'type': 'STRING', 'mode': 'NULLABLE'},
#      {'name': 'submittedDate', 'type': 'STRING', 'mode': 'NULLABLE'},
#      {'name': 'chamber', 'type': 'STRING', 'mode': 'NULLABLE'},
#      {'name': 'amendedBill',
#       'type': 'RECORD',
#       'mode': 'NULLABLE',
#       'fields': [{'name': 'congress', 'type': 'STRING', 'mode': 'NULLABLE'},
#        {'name': 'type', 'type': 'STRING', 'mode': 'NULLABLE'},
#        {'name': 'originChamber', 'type': 'STRING', 'mode': 'NULLABLE'},
#        {'name': 'originChamberCode', 'type': 'STRING', 'mode': 'NULLABLE'},
#        {'name': 'number', 'type': 'STRING', 'mode': 'NULLABLE'},
#        {'name': 'title', 'type': 'STRING', 'mode': 'NULLABLE'},
#        {'name': 'updateDateIncludingText',
#         'type': 'STRING',
#         'mode': 'NULLABLE'}]},
#      {'name': 'actions',
#       'type': 'RECORD',
#       'mode': 'NULLABLE',
#       'fields': [{'name': 'count', 'type': 'STRING', 'mode': 'NULLABLE'},
#        {'name': 'actions',
#         'type': 'RECORD',
#         'mode': 'NULLABLE',
#         'fields': [{'name': 'item',
#           'type': 'RECORD',
#           'mode': 'REPEATED',
#           'fields': [{'name': 'actionDate',
#             'type': 'STRING',
#             'mode': 'NULLABLE'},
#            {'name': 'sourceSystem',
#             'type': 'RECORD',
#             'mode': 'NULLABLE',
#             'fields': [{'name': 'code', 'type': 'STRING', 'mode': 'NULLABLE'},
#              {'name': 'name', 'type': 'STRING', 'mode': 'NULLABLE'}]},
#            {'name': 'text', 'type': 'STRING', 'mode': 'NULLABLE'},
#            {'name': 'type', 'type': 'STRING', 'mode': 'NULLABLE'},
#            {'name': 'actionTime', 'type': 'STRING', 'mode': 'NULLABLE'},
#            {'name': 'actionCode', 'type': 'STRING', 'mode': 'NULLABLE'},
#            {'name': 'recordedVotes',
#             'type': 'RECORD',
#             'mode': 'NULLABLE',
#             'fields': [{'name': 'recordedVote',
#               'type': 'RECORD',
#               'mode': 'NULLABLE',
#               'fields': [{'name': 'rollNumber',
#                 'type': 'STRING',
#                 'mode': 'NULLABLE'},
#                {'name': 'chamber', 'type': 'STRING', 'mode': 'NULLABLE'},
#                {'name': 'congress', 'type': 'STRING', 'mode': 'NULLABLE'},
#                {'name': 'date', 'type': 'STRING', 'mode': 'NULLABLE'},
#                {'name': 'sessionNumber', 'type': 'STRING', 'mode': 'NULLABLE'},
#                {'name': 'url', 'type': 'STRING', 'mode': 'NULLABLE'}]}]}]}]}]},
#      {'name': 'description', 'type': 'STRING', 'mode': 'NULLABLE'}]}]},
#  {'name': 'cdata', 'type': 'STRING', 'mode': 'NULLABLE'}]]

member_schema = [{'name': 'addressInformation',
  'type': 'RECORD',
  'mode': 'NULLABLE',
  'fields': [{'name': 'city', 'type': 'STRING', 'mode': 'NULLABLE'},
   {'name': 'district', 'type': 'STRING', 'mode': 'NULLABLE'},
   {'name': 'officeAddress', 'type': 'STRING', 'mode': 'NULLABLE'},
   {'name': 'phoneNumber', 'type': 'STRING', 'mode': 'NULLABLE'},
   {'name': 'zipCode', 'type': 'INT64', 'mode': 'NULLABLE'}]},
 {'name': 'bioguideId', 'type': 'STRING', 'mode': 'NULLABLE'},
 {'name': 'birthYear', 'type': 'STRING', 'mode': 'NULLABLE'},
 {'name': 'deathYear', 'type': 'STRING', 'mode': 'NULLABLE'},
 {'name': 'cosponsoredLegislation',
  'type': 'RECORD',
  'mode': 'NULLABLE',
  'fields': [{'name': 'count', 'type': 'INT64', 'mode': 'NULLABLE'},
   {'name': 'url', 'type': 'STRING', 'mode': 'NULLABLE'}]},
 {'name': 'currentMember', 'type': 'BOOLEAN', 'mode': 'NULLABLE'},
 {'name': 'depiction',
  'type': 'RECORD',
  'mode': 'NULLABLE',
  'fields': [{'name': 'attribution', 'type': 'STRING', 'mode': 'NULLABLE'},
   {'name': 'imageUrl', 'type': 'STRING', 'mode': 'NULLABLE'}]},
 {'name': 'directOrderName', 'type': 'STRING', 'mode': 'NULLABLE'},
 {'name': 'district', 'type': 'INT64', 'mode': 'NULLABLE'},
 {'name': 'firstName', 'type': 'STRING', 'mode': 'NULLABLE'},
 {'name': 'honorificName', 'type': 'STRING', 'mode': 'NULLABLE'},
 {'name': 'invertedOrderName', 'type': 'STRING', 'mode': 'NULLABLE'},
 {'name': 'lastName', 'type': 'STRING', 'mode': 'NULLABLE'},
 {'name': 'leadership',
  'type': 'RECORD',
  'mode': 'REPEATED',
  'fields': [{'name': 'congress', 'type': 'INT64', 'mode': 'NULLABLE'},
   {'name': 'current', 'type': 'BOOLEAN', 'mode': 'NULLABLE'},
   {'name': 'type', 'type': 'STRING', 'mode': 'NULLABLE'}]},
 {'name': 'officialWebsiteUrl', 'type': 'STRING', 'mode': 'NULLABLE'},
 {'name': 'partyHistory',
  'type': 'RECORD',
  'mode': 'REPEATED',
  'fields': [{'name': 'partyAbbreviation',
    'type': 'STRING',
    'mode': 'NULLABLE'},
   {'name': 'partyName', 'type': 'STRING', 'mode': 'NULLABLE'},
   {'name': 'startYear', 'type': 'INT64', 'mode': 'NULLABLE'},
   {'name': 'endYear', 'type': 'INT64', 'mode': 'NULLABLE'}]},
 {'name': 'sponsoredLegislation',
  'type': 'RECORD',
  'mode': 'NULLABLE',
  'fields': [{'name': 'count', 'type': 'INT64', 'mode': 'NULLABLE'},
   {'name': 'url', 'type': 'STRING', 'mode': 'NULLABLE'}]},
 {'name': 'state', 'type': 'STRING', 'mode': 'NULLABLE'},
 {'name': 'terms',
  'type': 'RECORD',
  'mode': 'REPEATED',
  'fields': [{'name': 'chamber', 'type': 'STRING', 'mode': 'NULLABLE'},
   {'name': 'congress', 'type': 'INT64', 'mode': 'NULLABLE'},
   {'name': 'district', 'type': 'INT64', 'mode': 'NULLABLE'},
   {'name': 'endYear', 'type': 'INT64', 'mode': 'NULLABLE'},
   {'name': 'memberType', 'type': 'STRING', 'mode': 'NULLABLE'},
   {'name': 'startYear', 'type': 'INT64', 'mode': 'NULLABLE'},
   {'name': 'stateCode', 'type': 'STRING', 'mode': 'NULLABLE'},
   {'name': 'stateName', 'type': 'STRING', 'mode': 'NULLABLE'}]},
 {'name': 'updateDate', 'type': 'STRING', 'mode': 'NULLABLE'},
 {'name': 'terms_all',
  'type': 'RECORD',
  'mode': 'NULLABLE',
  'fields': [{'name': 'item',
    'type': 'RECORD',
    'mode': 'REPEATED',
    'fields': [{'name': 'chamber', 'type': 'STRING', 'mode': 'NULLABLE'},
     {'name': 'startYear', 'type': 'INT64', 'mode': 'NULLABLE'},
     {'name': 'endYear', 'type': 'INT64', 'mode': 'NULLABLE'}]}]},
 {'name': 'middleName', 'type': 'STRING', 'mode': 'NULLABLE'},
 {'name': 'suffixName', 'type': 'STRING', 'mode': 'NULLABLE'},
 {'name': 'nickName', 'type': 'STRING', 'mode': 'NULLABLE'}]

senate_id_schema = [{'name': 'full_name', 'type': 'JSON', 'mode': 'NULLABLE'},
 {'name': 'publication_name', 'type': 'JSON', 'mode': 'NULLABLE'},
 {'name': 'party', 'type': 'STRING', 'mode': 'NULLABLE'},
 {'name': 'state', 'type': 'STRING', 'mode': 'NULLABLE'},
 {'name': 'bioguide', 'type': 'STRING', 'mode': 'NULLABLE'},
 {'name': 'service_dates', 'type': 'JSON', 'mode': 'NULLABLE'},
 {'name': 'death_date', 'type': 'JSON', 'mode': 'NULLABLE'},
 {'name': 'lisid', 'type': 'STRING', 'mode': 'REPEATED'},
 {'name': 'featured_bio', 'type': 'STRING', 'mode': 'NULLABLE'},
 {'name': 'current', 'type': 'STRING', 'mode': 'NULLABLE'}]

# senate_id_schema = [{'name': 'full_name',
#   'type': 'RECORD',
#   'mode': 'NULLABLE',
#   'fields': [{'name': 'first_name', 'type': 'STRING', 'mode': 'NULLABLE'},
#    {'name': 'middle_name', 'type': 'STRING', 'mode': 'NULLABLE'},
#    {'name': 'last_name', 'type': 'STRING', 'mode': 'NULLABLE'},
#    {'name': 'suffix', 'type': 'STRING', 'mode': 'NULLABLE'},
#    {'name': 'nickname', 'type': 'STRING', 'mode': 'NULLABLE'}]},
#  {'name': 'publication_name',
#   'type': 'RECORD',
#   'mode': 'NULLABLE',
#   'fields': [{'name': 'first_name', 'type': 'STRING', 'mode': 'NULLABLE'},
#    {'name': 'middle_name', 'type': 'STRING', 'mode': 'NULLABLE'},
#    {'name': 'last_name', 'type': 'STRING', 'mode': 'NULLABLE'},
#    {'name': 'suffix', 'type': 'STRING', 'mode': 'NULLABLE'},
#    {'name': 'nickname', 'type': 'STRING', 'mode': 'NULLABLE'}]},
#  {'name': 'party', 'type': 'STRING', 'mode': 'NULLABLE'},
#  {'name': 'state', 'type': 'STRING', 'mode': 'NULLABLE'},
#  {'name': 'bioguide', 'type': 'STRING', 'mode': 'NULLABLE'},
#  {'name': 'service_dates',
#   'type': 'RECORD',
#   'mode': 'NULLABLE',
#   'fields': [{'name': 'service_date',
#     'type': 'RECORD',
#     'mode': 'REPEATED',
#     'fields': [{'name': 'begin_date',
#       'type': 'RECORD',
#       'mode': 'NULLABLE',
#       'fields': [{'name': 'day', 'type': 'STRING', 'mode': 'NULLABLE'},
#        {'name': 'month', 'type': 'STRING', 'mode': 'NULLABLE'},
#        {'name': 'year', 'type': 'STRING', 'mode': 'NULLABLE'}]},
#      {'name': 'end_date',
#       'type': 'RECORD',
#       'mode': 'NULLABLE',
#       'fields': [{'name': 'day', 'type': 'STRING', 'mode': 'NULLABLE'},
#        {'name': 'month', 'type': 'STRING', 'mode': 'NULLABLE'},
#        {'name': 'year', 'type': 'STRING', 'mode': 'NULLABLE'}]}]},
#    {'name': 'note', 'type': 'STRING', 'mode': 'NULLABLE'}]},
#  {'name': 'death_date',
#   'type': 'RECORD',
#   'mode': 'NULLABLE',
#   'fields': [{'name': 'day', 'type': 'STRING', 'mode': 'NULLABLE'},
#    {'name': 'month', 'type': 'STRING', 'mode': 'NULLABLE'},
#    {'name': 'year', 'type': 'STRING', 'mode': 'NULLABLE'},
#    {'name': 'after_sine_die', 'type': 'STRING', 'mode': 'NULLABLE'},
#    {'name': 'congress', 'type': 'STRING', 'mode': 'NULLABLE'},
#    {'name': 'in_office', 'type': 'STRING', 'mode': 'NULLABLE'},
#    {'name': 'session', 'type': 'STRING', 'mode': 'NULLABLE'}]},
#  {'name': 'lisid', 'type': 'STRING', 'mode': 'REPEATED'},
#  {'name': 'featured_bio', 'type': 'STRING', 'mode': 'NULLABLE'},
#  {'name': 'current', 'type': 'STRING', 'mode': 'NULLABLE'}]