version: 2
sources:
  - name: staging
    database: "{{ env_var('DBT_GCP_PROJECT') }}"
    schema: Congress_Stg

    tables:
      - name: bills_External
      - name: house_votes_External
      - name: members_External
      - name: senate_ids_External
      - name: senate_votes_External

